site_name: Time Manager
site_description: Documentation du projet Time Manager

nav:
  - Accueil: index.md
  - DevOps: DEVOPS.md
  - API: API.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
